title = "GrapeMR bSSFP Configuration"

plot = true

[spins]
M0       = [0.0, 0.0, 1.0]
delta_B1 = [1.0]
offset   = 100.0
alpha    = "pi/3"
phase    = "2*pi"
TR       = 5e-3
intrinsics = [
    {T1 = 0.0319, T2 = 0.0266, label = "Water", target = "max"},
    #{T1 = 0.36, T2 = 0.22, label = "Glycerol", target = "min"}
]

[grape_parameters]
time_steps      = 1500
cost_function   = "saturation_contrast_Mx"
fields2optimize = [true, true, false]

[optimization_parameters]
hyper_opt    = false
poly_start   = 0.1
poly_degree  = 1.0
max_iter     =  9

[control_field]
control_time = 0.1
B1ref = 1.0

[save_files]
enabled = true
export_bruker = true
folder_path = "/path/to/save/files/"
bruker_folder_path = "/path/to/bruker/folder/"
