title = "GrapeMR Configuration"
plot = true

[spins]
M0 = [0.0, 0.0, 1.0]
delta_B1 = [1.0]
offset = 0.0
intrinsics = [{ T1 = 0.6, T2 = 0.3, label = "s1", target = "" }]

[grape_parameters]
time_steps = 2000
cost_function = "euclidean_norm"
fields2optimize = { "B1x" = true, "B1y" = true, "Bz" = false }


[optimization_parameters]
hyper_opt = false
poly_start = 0.1
poly_degree = 1
max_iter = 150

[control_field]
control_time = 0.5
B1ref = 1.0

[save_files]
enabled = false
export_bruker = false
folder_path = "/tmp/"
bruker_folder_path = "/tmp/"
